### ISSUE TITLE
Refactor Card component to account for changes in uids_base

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#104]
Per this diff: https://gist.github.com/pyrello/c42d50b20d83c9840970af6950a87534

How should we accommodate the differences in the SiteNow version of a card vs. the uiowa_blocks version of a card?

Should the subtitle and author fields be implemented as the same twig block in UIDS and then they are implemented as those specific fields in each entity-type specific template in uids_base? Or should we have both of them?

**Comment by bspeare** [comment]
@pyrello I think the author field has always been meant as a subtitle field so I would like to see those two combined. 

I have some refactoring that needs to be done to the card template based on https://github.com/uiowa/uids/issues/63. That I hope to add to https://github.com/uiowa/uiowa/pull/1329 today.

**Comment by joewhitsitt** [comment]
In reviewing the brand site, aria-describedby is hardcoded as "desc-a-card"

**Comment by bspeare** [comment]
@joewhitsitt Thanks.  The template definitely needs to be updated to reflect how card links are being implemented in SiteNow.

**Comment by bspeare** [comment]
@joewhitsitt Our current card setup with layout builder functions a bit differently.  If you look at https://uiowa.github.io/uids/components/preview/card-block--default.html there are a few options:

- If you provide `card_link_url` and `card_link_title` with a `card_title` it will create a faux button and set the link on the `<h3>` tag.    
- If you provide `card_link_url` and  leave `card_link_title` empty with a `card_title` it will just link up the `<h3` tag.  
- If you provide `card_link_url` and  leave `card_link_title` with an empty `card_title` it will just link up the `<h3` tag.  
- I didn't create a `card_image` variant because it seems like that could be accomplished though a WYSIWYG section easily. 

For Sitenow you have the `card_link_url` and `card_link_title` required and wrap the card with a `<div>` link.     Do you think it would be possible for the SiteNow card to move to linking up the `<h>` tag in the card and use the psuedo-content trick to make the card clickable instead? This would also create a faux button like on https://uiowa.github.io/uids/components/preview/card-block--default.html.

**Comment by joewhitsitt** [comment]
I wasn't very comfortable with the current card link functionality in SiteNow. Yeah I think SiteNow can make that switch without much trouble, assuming the faux button is a11y-okay.

I think the card image is a harder sell but we can talk more about that.

**Comment by bspeare** [comment]
That sounds like a good plan.   Do you see an advantage of image only card implementation? Do you see a lot of them in use? 

It does seem difficult to add a link to an image in the SiteNow WYSIWYG.  Adding one on uiowa.edu seems a lot easier - is that because of the core media solution?

**Comment by joewhitsitt** [comment]
We haven't had the use-case yet for the 80% SiteNow, but image with text overly was a feature we added for HR and I could see that being something that more folks want.
<img width="555" alt="Screen Shot 2020-04-21 at 1 23 02 PM" src="https://user-images.githubusercontent.com/4663676/79900053-422ffa00-83d3-11ea-9d8c-0d93887cce15.png">

**Comment by bspeare** [comment]
I'd be interested in that variant.   That way we could still add the link to the text overlay and use the psuedo-content trick to make the image clickable.

**Comment by joewhitsitt** [comment]
I don't recall how it works if card subtitle/body text is also supplied besides training them not to, but here are HR specific style options:

<img width="325" alt="Screen Shot 2020-04-21 at 1 33 21 PM" src="https://user-images.githubusercontent.com/4663676/79901083-e23a5300-83d4-11ea-852e-1e301e9d5521.png">

**Comment by pyrello** [comment]
Just want to respond to a few things here:

> Do you see an advantage of image only card implementation? Do you see a lot of them in use?

It is my opinion that an image-only card is not in fact a card, whether it is linked or not. If there is demand for an image-only component, let's add that and make it linkable. Otherwise, I think we are stretching the definition of what a card is too much for it to really be meaningful.

With regard to how we can accommodate the fact that it is technically possible to create an image-only card in SiteNow, I think we should just check in the paragraph card template in uids_base and render the output differently for this edge case.

> We haven't had the use-case yet for the 80% SiteNow, but image with text overly was a feature we added for HR and I could see that being something that more folks want.
><img width="555" alt="Screen Shot 2020-04-21 at 1 23 02 PM" src="https://user-images.githubusercontent.com/4663676/79900053-422ffa00-83d3-11ea-9d8c-0d93887cce15.png">

I also don't believe that this should be a card. It looks closer to a banner or hero component to me. Again, I think that it is stretching the definition of a card too much that it starts to become meaningless. I think that having clear guidelines around what constitutes a component will make it easier for site editors to know what they should and should not do.

I would propose that a card must contain 2 or more of the following fields:
* Image
* Title
* Body

It can be linked or not, and based on the criteria specified in @bspeare's comment above (https://github.com/uiowa/uids/issues/104#issuecomment-616814344), it can potentially show a faux button (assuming this passes a11y scrutiny), or just contain the link in the title of the card.

A card can also optionally contain the following fields:
* Subtitle
* Date
* Author - I'm still fine with this and subtitle being combined into one field or having them both display separately.

A card has the following orientations:
* Portrait (stacked) (default)
* Landscape (horizontal) - In mobile, I'm assuming these both collapse to Portrait.

A card has the following style variations:
* Open - no outline
* Enclosed - outline
* Possibly additional style variations yet to be determined

Anything that does not meet the above criteria is not a card and should be part of the definition of a different component.

**Comment by joewhitsitt** [comment]
>Must contain 2 or more of the following fields

Are you proposing validation on this? By this definition and "Possibly additional style variations yet to be determined," the HR image card is technically a card.

- I see the possibility of author and subtitle being styled different and in my opinion house two different kinds of content (supplemental identification of content and meta information), so I'd like to keep the fields separate and optional.

- I think having orientations is good but should optional configuration because of the singular by default setup of SiteNow. Because of mobile, I find the terminology of portrait/landscape a bit more confusing than list/grid, but I am definitely a developer in that sense and not a content editor who also works with print.

- A style variation that I have seen in the design meetings is the icon circle with portrait/list.

- Overall, I am fine with narrowing the definition of a card. When we were building SiteNow, it just seemed like everything was some kind of title/content that could easily be grouped up as a "card." In fact, if I were to do it over again, I would reconsider the idea of a generic list/list item component with different view modes and style options. I can't remember where I saw this, but at the time I was was thinking "WE HAVE TO GO BACK"

![](https://media.giphy.com/media/BF4npXkyM4ZsA/source.gif)

This allows static custom content to stay in the same bucket and not have to migrate/move from block/paragraph cards to accordions to definition list to list group to tabs to...

- It is important to me that we keep track of these "breaking changes" so we can audit and move content to the right bucket (e.g. HR) when the time comes to switch.

**Comment by pyrello** [comment]
>Are you proposing validation on this? 

Not in UIDS. Not necessarily in uids_base either. This is meant to be a standard. It doesn't need to be strictly enforced to be a standard.

> By this definition and "Possibly additional style variations yet to be determined," the HR image card is technically a card.

I attempted to write some text to clarify the intent here: https://github.com/uiowa/uids/pull/150/files#diff-cfc0128c94e40c4faa426d25d9c6e7d9R2

My point is that cards should not be text/buttons sitting on top of cards. I think that should be something else.

> I see the possibility of author and subtitle being styled different and in my opinion house two different kinds of content (supplemental identification of content and meta information), so I'd like to keep the fields separate and optional.

Sounds good to me.

> I think having orientations is good but should optional configuration because of the singular by default setup of SiteNow. Because of mobile, I find the terminology of portrait/landscape a bit more confusing than list/grid, but I am definitely a developer in that sense and not a content editor who also works with print.

I'm not married to the portrait/landscape terminology. I was trying to think about ways to refer to standard and horizontal cards in a different way.

To some degree, I think the distinction is actually kind of moot. A horizontal card behaves like a standard card below a certain breakpoint. A card that is not contained within columns should probably be styled like a horizontal card because a "standard" card that spans the whole content container is not a pretty thing. To some degree the `.card--horizontal` class is an artificial thing that is necessitated by the fact that we can't do a media query against the container to see how big it is. If we could, then we could just automatically render a horizontal card past a certain parent container size and a standard card below a certain container size.

> A style variation that I have seen in the design meetings is the icon circle with portrait/list.

An image style as a circle in a card is something being used in events, which seem to also be cards. Is that a style of the card? Or a style that can be applied to the image?

> Overall, I am fine with narrowing the definition of a card. When we were building SiteNow, it just seemed like everything was some kind of title/content that could easily be grouped up as a "card." In fact, if I were to do it over again, I would reconsider the idea of a generic list/list item component with different view modes and style options. I can't remember where I saw this, but at the time I was was thinking "WE HAVE TO GO BACK"
>
>This allows static custom content to stay in the same bucket and not have to migrate/move from block/paragraph cards to accordions to definition list to list group to tabs to...

Part of the underlying change in how the design system is structured that is being discussed is how to represent collections of items. Currently we represent items as part of their collection. What I would like to see is each item represented as an individual thing, then its possible implementation in lists/grids/masonry be represented as a separate thing. Maybe we have card-specific collections, or maybe we just use cards to represent the options for different types of collections.

> It is important to me that we keep track of these "breaking changes" so we can audit and move content to the right bucket (e.g. HR) when the time comes to switch.

Should we start an issue to track what maps to what? Would you want to create that? I think you have a better sense of it at this point than I do.

**Comment by bspeare** [comment]
Just to clarify, the `card--horizontal` variation is meant for a lists like on https://brand.prod.drupal.uiowa.edu/news and https://uiowa.stage.drupal.uiowa.edu/admissions.  so I could see the terminology adjusted since a grid/list variation makes more sense than standard/horizontal.   

Regarding:

- Overall, I am fine with narrowing the definition of a card. When we were building SiteNow, it just seemed like everything was some kind of title/content that could easily be grouped up as a "card." In fact, if I were to do it over again, I would reconsider the idea of a generic list/list item component with different view modes and style options. I can't remember where I saw this, but at the time I was was thinking "WE HAVE TO GO BACK"

@joewhitsitt Can you elaborate on this?  I like the simplicity of how you built everything to extend the card style in some way.  How would you like to see this changed?

**Comment by joewhitsitt** [comment]
Oops. Sorry, followed a link and forgot this was a UIDS task so a lot of my comments Drupal paragraph/block specific.

To elaborate, I saw an example somewhere of a paragraph implementation that was heavily focused on this grouped "card" (image, title (required), content, link) that that could be changed at the group level to any number of things:

- UL (like bootstrap's listgroup and all those options)
- OL
- Defintion List
- Accordion list
- grid of cards
- group of tabs
- timeline


Basically, all of these things are either a ul, ol, dl of things requiring at least a "title" for the most minimal render, administrative identification and accessible alt.

Based on the "view mode" that is selected, view mode specific styles/options would be available. Overall it provides consistent structure of content (better SEO, a11y, predictable html markup to base design patterns off of) if you are willing to abandon or separate out a singular item.

To approach this today, I would probably refactor SiteNow accordion to work this way with existing keeping the accordion setup and new items defaulting to ul. SiteNow would probably keep the singular card for for those matchups of different content/column widths.

I don't mean to hijack this issue with these should of/could of SiteNow/Drupal things, but if folks are interested in this idea, the default markup to serve as the base of all this would be very `<ul>` like.

**Comment by joewhitsitt** [comment]
I forgot to mention, I will try to stay on top of the breaking changes that affect SiteNow sites and make follow-up issues as they come up. I have little knowledge of the collegiate profile and what changes need to happen to adopt. Thankfully, the customizations on SiteNow side are still limited to just a couple sites. The biggest thing will be whether or not to account for all of the possible bootstrap classes that could be used currently in WYSIWYGs

**Comment by pyrello** [comment]
@joewhitsitt @bspeare It sounds like there are no objections to this card definition? If so I'm going to move forward with this idea in mind. We don't have to consider it set in stone, as in there is no changing it, but just that it is our definition for now.

**Comment by pyrello** [comment]
Do you think we can consider this task completed?
