### ISSUE TITLE
Banner vs Hero? What's the difference?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#224]
I think that banner and hero components are very similar and we should at least consider consolidating them down into one component unless we can clearly articulate what their differences are and why those differences are important. I also think this needs to happen before we invest too much time into rewriting the hero component.

@bspeare Any insight you can provide into what the intention behind creating these two components is much appreciated :)

**Comment by bspeare** [comment]
@pyrello the banner was built for the first iteration of HDS and the hero was built for the design that was generated post-HDS.   I'm fine with consolidating them into one component.

**Comment by bspeare** [comment]
**Banner**

The banner component is meant to take up a smaller vertical footprint on each page and provide an accessible CTA method while featuring a full-width background image.  This component is often used further down the page below the hero and body text to draw visual attention to a secondary conversion goal or message that was not accomplished within the Hero or body copy.  Possible refactoring could include a centered option and a smaller vertical height so that it could be used above a hero or page title potentially. 

- Color reversed options with left black and white gradients
- Background Image, Title, Body, and Link button are available
- Thin image crop so that it truly is a more like a "banner"
- Now used in Slider component
- Has a smaller heading size, light font weight
- Could possibly create a variant and become https://github.com/uiowa/uids/issues/107.  

**Hero**
The hero component is often the first visual element a visitor encounters on the site; it presents an overview of the site's most important content or CTA links.  A hero consists of a headline, image/video and text.  Special design considerations have been made around the hero to accommodate for pause/play button and `vh` to keep the hero content appear above the fold when this component is used as the first item on the page. 

- Large Image style sets itself up to be a "hero"
- Heading size is very large
- Existing Variants
-- Left Aligned Hero
  -- Page title hero with breadcrumbs
  -- Heading and Body text of regular weight
-- Center Aligned Hero
 -- Heading and Body text of regular weight
-- Two column grid option seen in the "Welcome Home" component on uiowa.edu
-- Video variant for centered and left align versions
- https://github.com/uiowa/uids/issues/248 Requested variant on the heading to have the highlight treatment
- Refactor should address https://github.com/uiowa/uids/issues/245 and https://github.com/uiowa/uids/issues/243

**Comment by bspeare** [comment]
If we merged these two it would look like:
- Centered / Left Aligned
- Bottom Gradient and Left Gradient / white and black
- Small, Medium, and Large crop options that alter text sizes and weights based on size selection
- Remove filtered_html option for content area and use a text or minimal_html text area
- Add dedicated link field for one CTA link
- Heading variant using the gold background highlighted style
- Video variant

**Comment by bspeare** [comment]
These components were merged and this work is complete.
