### ISSUE TITLE
Set an overflow solution for default tables

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#510]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

Default tables need to have a simple horizontal overflow option that allows them to be used in thin widths.

# Proposed solution

1. Remove responsive functionality from triggering on any table.
2. Style Tables with a simple overflow horizontally

**Comment by GaryRidgway** [comment]
This will include adding a wrapping div to every table. @pyrello and I have talked about this and we think that for the best US and database consistent reasons that a dif should be wrapped around the tables in CKEDITOR before save. This would require an update hoo, likely done in batch with https://github.com/uiowa/uiowa/issues/3330, to wrap all previous tables with this same div.

**Comment by joewhitsitt** [comment]
> we think that for the best US and database consistent reasons that a div should be wrapped around the tables in CKEDITOR before save.

What?

**Comment by GaryRidgway** [comment]
Sorry, maybe I wasn't clear enough, and obviously I misspelled UX. Fixed that. I mean to say that editing the DOM with JS at HTML generation to add a div every time is something we would like to try and avoid. Therefore, we would like to hook in to CKEditor and wrap the div around the table on save instead.

**Comment by joewhitsitt** [comment]
I am not sure how the UX changes with this. In both situations, the editor is not involved with wrapping the table with the responsive div. If anything, I see a greater chance of database corruption with looking through the field value and injecting a change that is then saved to the db.

**Comment by pyrello** [comment]
Here's what we are looking at:
* To the best of my knowledge, we need a wrapping `<div class="table--responsive"></div>` to get the horizontal scroll effect that we are going to move to as our default responsive solution. This is consistent with how Bootstrap handles it.
* The current responsive solution handles this need by using a javascript to find all the tables in the DOM and wrapping them with similar markup. Because this is done as a progressive enhancement, we have to have the extra overhead to run this logic every time the page loads for every table on the page. We incur this extra performance cost even if the page is served from the Varnish cache.
* Alternately, if we can find a way to ensure that the table markup has the necessary wrapping div added through some PHP mechanism, we can have it run only as often as the cache gets regenerated.
* CKEditor is already responsible for generating and correcting/fixing markup. I haven't worked with it before, so I'm not exactly sure how it works, but I'm under the impression that we could hook into the current process of generating the table markup and add the extra div. There are surely going to be some gotchas with this approach - for example, if someone deletes the closing `</div>` of the wrapper. But it certainly seem conceivable that we could figure it out and that it could be tested to the point where we have confidence in its proper functioning. If we were able to get this working then, we would only incur the extra overhead whenever CKEditor has to create/refresh the markup or on each save, which would happen the most rarely of all these scenarios.
* Or... if you have a better idea of how to accomplish the above, we are definitely open to other ideas :)

**Comment by bspeare** [comment]
There are CSS only solutions for the simple responsive table: https://codepen.io/dbushell/full/wGaamR.   Do we really need to wrap it in a `<div>`?

**Comment by joewhitsitt** [comment]
It still isn't clear to me that you aren't trying to do this during a presave or something and updating databases to "fix" and maintain this functionality. I am still against that.

I am open to a CKEditor filter, similar to LinkIt and Media that changes markup on render and then is cached.

I am also open to the CSS only solution since this is progressive enhancement and we don't need it to support every browser.

**Comment by GaryRidgway** [comment]
@bspeare  Thats pretty awesome! I thought you needed a wrapping div for them, but if you dont thats great!
