### ISSUE TITLE
Implement accessibility updates to card and events component

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#63]
- https://inclusive-components.design/cards/
- https://heydon.github.io/Inclusive-Components/cards-redundant-click-read-more/

Subgrid might also be useful:
https://codepen.io/mirisuzanne/pen/xxKRpmq?editors=1100

**Comment by inspector508** [comment]
The Pickering examples seem pretty good for kbd and SR  They check all of the boxes in two key browser environments (NVDA/FF; NVDA/Chrome). IE11 is a much different experience (for the Pickering cards), since they don't tile and the link focus is visible on the <h2><a>, rather than the faux <span>. Main issue: reading with directional arrows, screen readers jump over faux <span> button, which puts call to action before card content--make "Read More" button focusable with description from <h2>?? Could be best to treat these much like modals.

Subgrid examples did not seem too good in terms of tab or keyboard order. They hit <h_n_> tags but no better than Pickering.

As a relatively new pattern, I'd consider Pickering (with tests for use cases; no flipcard yet). This pattern could change any time, so semantic stability is key.
