### ISSUE TITLE
4.x - Provide base CSS stylesheets

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#908]
## Story 

As a user of uids.brand.uiowa.edu, I can copy and paste markup and CSS from each component to use on my website or application. 

# 3.x Solution
For 3.x we have been providing CSS on https://brand.uiowa.edu/applying-brand/web#heading6951:
```
To utilize the brand bar on your website or application, you will need to use the following CSS files in the order that they are listed below.

    https://github.com/uiowa/uids/blob/main/dist/css/fonts.css
    https://github.com/uiowa/uids/blob/main/dist/css/reset.css
    https://github.com/uiowa/uids/blob/main/dist/css/components/iowa-bar.css

```

# Proposed  4.x Solution
- [ ] Define a build process to produce the assets defined above from 3.x solution
- [ ] Build it!!!

**Comment by bspeare** [comment]
This might be blocked until https://github.com/uiowa/uids/issues/900 is complete.

**Comment by pyrello** [comment]
> Maybe https://storybook.js.org/addons/display-element-css is worth trying first?

I'm assuming that this is something that outputs CSS that can be viewed and copied. I would argue that displaying the CSS rather than providing links that we intend to keep in place over time is going to exacerbate the issue we have where people consume UIDS by copying/pasting rather than directly using the assets. I think we should be focusing on trying to get to a point where people can reliably consume the assets because anything else is a maintenance headache for the implementing app and a support headache for us.

**Comment by briand44** [comment]
Future slice for all components can be done in consultation with partners so they can weigh in on what would be most valuable to them.
