### ISSUE TITLE
UIDS automation is failing: https://github.com/uiowa/uids/actions/runs/9151455282

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#927]
https://github.com/uiowa/uids/actions/runs/9151455282
```[tasklist]
### Tasks
- [x] Update dependencies in both workflows
- [x] Confirm that branch docs still build for PR branch
```

**Comment by joewhitsitt** [comment]
Grooming convo: Suspect that the workflow file's dependencies need to be updated to work with more recent versions of Node. Due to re-running automations this could take a bit to ensure things are good. Other github actions automations could be affected but shouldn't add much to size. Impact is that this cleans up our old branches.

**Comment by pyrello** [comment]
I'm going to poke at this.

**Comment by pyrello** [comment]
Since the stale branches workflow uses the same dependencies as the GH pages workflow, it is my assumption that if updating the dependencies for the GH pages workflow works, then it will also work for the stale branches. Based on that, I don't think it is necessary to specifically test the stale branches workflow as part of this. Rather, after we have confirmed that updating the dependencies works with the GH pages workflow, we should merge the PR with the assumption that we have fixed the stale branches workflow and then confirm when it runs the next time.
